In [2]:
import torch

# Tensor

Tensor : '데이터를 표현하는 단위'

## Scalar

Scalar : 상숫값 , 하나의 값을 표현할 때 1개의 수치로 표현한 것

In [4]:
scalar1 = torch.tensor([1.])
print(scalar1)

scalar2 = torch.tensor([3.])
print(scalar2)

tensor([1.])
tensor([3.])


In [5]:
add_scalar = scalar1 + scalar2
print(add_scalar)


sub_scalar = scalar1 - scalar2
print(sub_scalar)

mul_scalar = scalar1 * scalar2
print(mul_scalar)

div_scalar = scalar1 / scalar2
print(div_scalar)

tensor([4.])
tensor([-2.])
tensor([3.])
tensor([0.3333])


In [6]:
# torch 내장 모듈 활용하여 사칙연산 하기
print(torch.add(scalar1,scalar2))
print(torch.sub(scalar1,scalar2))
print(torch.mul(scalar1,scalar2))
print(torch.div(scalar1,scalar2))

tensor([4.])
tensor([-2.])
tensor([3.])
tensor([0.3333])


## Vector

Vector : 하나의 값을 표현할 때 2개 이상의 수치로 표현한 것

In [7]:
vector1 = torch.tensor([1.,2.,3.])
print(vector1)

vector2 = torch.tensor([4.,5.,6.])
print(vector2)

tensor([1., 2., 3.])
tensor([4., 5., 6.])


In [13]:
add_vector = vector1 + vector2
print(add_vector)

sub_vector = vector1 - vector2
print(sub_vector)

mul_vector = vector1 * vector2
print(mul_vector)

div_vector = vector1 / vector2
print(div_vector)

tensor([5., 7., 9.])
tensor([-3., -3., -3.])
tensor([ 4., 10., 18.])
tensor([0.2500, 0.4000, 0.5000])


In [9]:
# torch 내장 모듈 활용하여 vector 연산하기
print(torch.add(vector1,vector2))
print(torch.sub(vector1,vector2))
print(torch.mul(vector1,vector2))
print(torch.div(vector1,vector2))

tensor([5., 7., 9.])
tensor([-3., -3., -3.])
tensor([ 4., 10., 18.])
tensor([0.2500, 0.4000, 0.5000])


## 행렬

행렬 : 2개 이상의 벡터 값을 통합해 구성된 값
--> 벡터 값 간 연산 속도를 빠르게 진행할 수 있는 선형대수의 기본 단위

In [12]:
matrix1 = torch.tensor([[1.,2.],[3.,4.]])
print(matrix1)
matrix2 = torch.tensor([[5.,6.],[7.,8.]])
print(matrix2)

tensor([[1., 2.],
        [3., 4.]])
tensor([[5., 6.],
        [7., 8.]])


In [14]:
sum_matrix = matrix1 + matrix2
print(sum_matrix)

sub_matrix = matrix1 - matrix2
print(sub_matrix)

mul_matrix = matrix1 * matrix2
print(mul_matrix)

div_matrix = matrix1 / matrix2
print(div_matrix)

tensor([[ 6.,  8.],
        [10., 12.]])
tensor([[-4., -4.],
        [-4., -4.]])
tensor([[ 5., 12.],
        [21., 32.]])
tensor([[0.2000, 0.3333],
        [0.4286, 0.5000]])


In [15]:
# torch 내장 모듈 활용하여 matrix 연산하기
print(torch.add(matrix1,matrix2))
print(torch.sub(matrix1,matrix2))
print(torch.mul(matrix1,matrix2))
print(torch.div(matrix1,matrix2))


# 행렬곱 연산
print(torch.matmul(matrix1, matrix2))

tensor([[ 6.,  8.],
        [10., 12.]])
tensor([[-4., -4.],
        [-4., -4.]])
tensor([[ 5., 12.],
        [21., 32.]])
tensor([[0.2000, 0.3333],
        [0.4286, 0.5000]])
tensor([[19., 22.],
        [43., 50.]])


## 텐서

행렬을 2차원 배열이라 표현한다면, 텐서는 2차원 이상의 배열이라 표현할 수 있다.

In [16]:
tensor1 = torch.tensor([[[1.,2.],[3.,4.]],[[5.,6.],[7.,8.]]])
print(tensor1)
tensor2 = torch.tensor([[[9.,10.],[11.,12.]],[[13.,14.],[15.,16.]]])
print(tensor2)

tensor([[[1., 2.],
         [3., 4.]],

        [[5., 6.],
         [7., 8.]]])
tensor([[[ 9., 10.],
         [11., 12.]],

        [[13., 14.],
         [15., 16.]]])


In [17]:
sum_tensor = tensor1 + tensor2
print(sum_tensor)

sub_tensor = tensor1 - tensor2
print(sub_tensor)

mul_tensor = tensor1 * tensor2
print(mul_tensor)

div_tensor = tensor1 / tensor2
print(div_tensor)

tensor([[[10., 12.],
         [14., 16.]],

        [[18., 20.],
         [22., 24.]]])
tensor([[[-8., -8.],
         [-8., -8.]],

        [[-8., -8.],
         [-8., -8.]]])
tensor([[[  9.,  20.],
         [ 33.,  48.]],

        [[ 65.,  84.],
         [105., 128.]]])
tensor([[[0.1111, 0.2000],
         [0.2727, 0.3333]],

        [[0.3846, 0.4286],
         [0.4667, 0.5000]]])


In [18]:
# torch 내장 모듈 활용하여 tensor 연산하기
print(torch.add(tensor1,tensor2))
print(torch.sub(tensor1,tensor2))
print(torch.mul(tensor1,tensor2))
print(torch.div(tensor1,tensor2))


# 텐서곱 연산
print(torch.matmul(tensor1, tensor2))

tensor([[[10., 12.],
         [14., 16.]],

        [[18., 20.],
         [22., 24.]]])
tensor([[[-8., -8.],
         [-8., -8.]],

        [[-8., -8.],
         [-8., -8.]]])
tensor([[[  9.,  20.],
         [ 33.,  48.]],

        [[ 65.,  84.],
         [105., 128.]]])
tensor([[[0.1111, 0.2000],
         [0.2727, 0.3333]],

        [[0.3846, 0.4286],
         [0.4667, 0.5000]]])
tensor([[[ 31.,  34.],
         [ 71.,  78.]],

        [[155., 166.],
         [211., 226.]]])


# Autograd

파이토치를 이용해 코드를 작성하면 back propagation을 이용해 파라미터를 업데이트한다.
이는 Autograd 방식으로 쉽게 구현이 가능하도록 설정되어있다.

In [20]:
# torch.cuda.is_available() : torch module을 이용할 때 GPU를 이용해 계산할 수 있는지 확인하는 method
if torch.cuda.is_available() :
    DEVICE = torch.device('cuda')
else :
    DEVICE = torch.device('cpu')

In [21]:
'''
BATCH_SIZE
BATCH_SIZE : 파라미터를 업데이트할 때 계산되는 데이터의 개수
BATCH_SIZE 수만큼 데이터를 이용해 output을 계산하고 BTACH_SIZE 수만큼 출력된 결과값에 대한 오차 계산
BATCH_SIZE 수만큼 계산된 오차의 평균하여 Back propagation 적용하여 파라미터 업데이트한다.
즉 , input으로 사용되는 데이터 개수가 64개라는 뜻이다.

INPUT_SIZE
input 크기이자, 입력층의 노드 수 --> 입력 데이터의 크기가 1000
이는 (64,1000)으로 1000크기의 벡터 값을 64개 사용한다는 의미이다.

HIDDEN_SIZE
input을 다수의 파라미터를 이용해 계산한 결과에 한 번 더 계산되는 파라미터 수를 의미한다.
(64,1000)의 input들이 (1000,100) 크기의 행렬과 행렬 곱을 계산하기 위해 설정한 수이다.

OUTPUT_SIZE
최종으로 출력되는 값의 벡터의 크기 -> 최종으로 비교하고자 하는 레이블의 크기와 동일하게 설정
ex) 10개로 분류한다면 크기가 10짜리인 one-hot encoding을 이용하기 위해 output 크기를 10으로 한다.


'''

BATCH_SIZE = 64 
INPUT_SIZE = 1000 
HIDDEN_SIZE = 100
OUTPUT_SIZE = 10

In [22]:
# randn : 평균이 0, 표준편차가 1인 정규분포애서 샘플링한 값
x = torch.randn(BATCH_SIZE, 
                INPUT_SIZE, 
                device = DEVICE, 
                dtype = torch.float, 
                requires_grad = False)

y = torch.randn(BATCH_SIZE, 
                OUTPUT_SIZE, 
                device = DEVICE, 
                dtype = torch.float, 
                requires_grad = False)

# requires_grad = True : gradient를 계산할 수 있도록 설정
w1 = torch.randn(INPUT_SIZE, 
                HIDDEN_SIZE, 
                device = DEVICE, 
                dtype = torch.float, 
                requires_grad = True)

# w2는 w1과 x를 행렬 곱한 결과에 계산할 수 있는 데이터
# w1과 x의 행렬곱한 결과 : (1,100) 
# 따라서 (10,)output을 계산할 수 있도록 (100,10)행렬 이용
w2 = torch.randn(HIDDEN_SIZE, 
                OUTPUT_SIZE, 
                device = DEVICE, 
                dtype = torch.float, 
                requires_grad = True)

In [24]:
learning_rate=1e-6 # gradient 값에 따른 학습 속도 결정
                    # 파라미터 업데이트 시, gradient를 계산한 결과 값에 learning_rate만큼 곱한 값을 이용해 업데이트

for t in range(1,501) :
    y_pred = x.mm(w1).clamp(min=0).mm(w2) # x와 w1간의 헹렬 곱을 이용해 나온 값 계산
                                          # clamp : torch 내 비선형 함수 적용 (ex. ReLU)
                                          # 딥러닝 모델에서는 층과 층 사이에서 비선형 함수를 이용해 높은 표현력을 지니는 방정식을 얻는다.
                                          # clamp로 나온 결과값과 w2의 행렬곱 수행
        
    
    loss = (y_pred-y).pow(2).sum() # 오차계산
    if t%100 == 0:
        print("Iteration : ",t ,"\t", "Loss : ", loss.item())
    loss.backward() # backward() : 각 파라미터에 대해 gradient를 계산하고, back propagation을 진행한다는 것을 의미 
    
    
    # 각 파라미터 값에 대해 gradient 계산한 결과를 이용해 파라미터 값을 업데이트 할 때는ㄴ 해당 시점의 gradient 값을 고정한 후, 업데이트 한다.
    with torch.no_grad(): 
        # 빼는 이유 : loss 값이 최소로 계산될 수 있는 파라미터 값을 찾ㅈ기 위해 gradient 값에 대한 반대 방향으로 계산한다는 것을 의미
        w1 -= learning_rate * w1.grad
        w2 -= learning_rate * w2.grad
        
        # 파라미터 값을 업데이트한 후, gradient를 초기화해 다음 반복문을 수행할 수 있도록 gradient 값을 0으로 설정한다.
        w1.grad.zero_()
        w2.grad.zero_()

Iteration :  100 	 Loss :  387.2408752441406
Iteration :  200 	 Loss :  1.416290044784546
Iteration :  300 	 Loss :  0.008046019822359085
Iteration :  400 	 Loss :  0.00018531134992372245
Iteration :  500 	 Loss :  3.5736218706006184e-05
